spring:
  application:
    name: st-microservice-filemanager

server:
  port: 8886
  max-http-header-size: 10000000 
  
logging:
  level:
    org:
      hibernate:
        SQL: debug

endpoint: filemanager