spring:
  application:
    name: st-microservice-filemanager
  main:
    allow-bean-definition-overriding: true

server:
  port: 8886
  max-http-header-size: 10000000 
  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
  
logging:
  level:
    org:
      hibernate:
        SQL: debug

endpoint: filemanager